sudo: false
install: true

script:
  - mvn install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
before_deploy:
  # Set up git user name and tag this commit
  - git config
  
